name: Build Iris Mlops Pipeline Docker Image
run-name: ${{ github.actor }} is building container image
on:
  push:
    branches: [ main ]
          
 workflow_dispatch:
  
env:
    REGISTRY_URL: ghcr.io/purnendrakumar
    IMAGE_NAME: iris-mlops-pipeline
jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            attestations: write
            id-token: write
        steps:
            - run: echo "🎉 Triggered by a ${{ github.event_name }} event."

            - run: echo "🔎 ${{ github.repository }} ${{ github.ref }}"

            - name: Check Out
              uses: actions/checkout@v4
            
            - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

            - name: Release Version
              id: release
              shell: bash
              run: |
                version=$(rep myproject requirements.txt | cut -d'=' -f3)
                echo "Building release version $version"
                echo "RELEASE_VERSION=$version" >> $GITHUB_ENV
                
            - name: Build Docker Image
              run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}:$RELEASE_VERSION --label "runnumber=${{ github.run_id }}"
            
            - name: GHCR Login
              run: |
                echo "Logging in to ghcr.io with username: ${{ github.actor }}"
                echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            - name: Tag Image Version
              run: docker tag ${{ env.IMAGE_NAME }}:$RELEASE_VERSION ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:$RELEASE_VERSION
            
            - name: Push Docker Image
              run: docker push ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:$RELEASE_VERSION
            
            - name: Remove Registry Image
              run: docker rmi ${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:$RELEASE_VERSION
                        
            - name: Remove Local Image
              run: docker rmi ${{ env.IMAGE_NAME }}:$RELEASE_VERSION
